fix server daemon to be something more flexible
fix bug in deploy script

add correct deploy to for start script

diff --git a/templates/default/goapp-server-daemon.erb b/templates/default/goapp-server-daemon.erb
--- a/templates/default/goapp-server-daemon.erb
+++ b/templates/default/goapp-server-daemon.erb
@@ -1,17 +1,56 @@
-#!/bin/sh
+#!/bin/sh -e
+
+set -e
+
+. /lib/lsb/init-functions
+
+USER="deploy"
+GROUP="www-data"
+NAME="goapp_<%= @application_name %>_server"
+ROOT="<%= @deploy_to %>"
+PIDFILE="$ROOT/shared/pids/goapp.pid"
+
+start() {
+    local options
+    pidfile=$(printf "$PIDFILE")
+    setcap 'cap_net_bind_service=+ep' <%= @release_path %>/bin/$NAME
+
+    options="-c <%= @config_file %> -custom_config_path=<%= @custom_config_path %>"
+    if start-stop-daemon --start --background --chdir <%= @release_path %> --chuid $USER:$GROUP --make-pidfile --pidfile $pidfile --exec <%= @release_path %>/bin/$NAME -- $options
+    then
+        log_daemon_msg "Starting Go Application: $NAME ..."
+    else
+        log_failure_msg "Failed to start Go Applicaiton: $NAME!"
+    fi
+}
+
+stop() {
+    local pidfile
+    setcap 'cap_net_bind_service=-ep' <%= @release_path %>/bin/$NAME
+
+    pidfile=$(printf "$PIDFILE")
+
+    if start-stop-daemon --stop --quiet --oknodo --pidfile $pidfile
+    then
+        log_daemon_msg "Stopped Go Application: $NAME"
+        rm -f $pidfile
+    else
+        log_failure_msg "Failed to stop Go Application: $NAME!" >&2
+    fi
+}
 
 case $1 in
-  start)
-     echo $$ > <%= @pid_file %>;
-     cd <%= @release_path %>;
-     exec 2>&1 <%= @release_path %>/bin/goapp_<%= @application_name %>_server -c <%= @config_file %> -custom_config_path=<%= @custom_config_path %>  1>><%= @output_file %>
-     ;;
-   stop)
-     kill `cat <%= @pid_file %>` ;;
-   restart)
-     stop ; echo "Sleeping..."; sleep 1 ;
-     start
-     ;;
+    start)
+        start
+        ;;
+    stop)
+        stop
+        ;;
+    restart)
+        stop
+        echo "Sleeping..."; sleep 1 ;
+        start
+        ;;
    *)  
      echo "usage: goapp-<%= @application_name %>-server-daemon {start|stop|restart}" ;;
 esac
